name:                aoc2021
version:             0.1.0.0
github:              "githubuser/aoc2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- hashable

library:
  source-dirs: src
  ghc-options:
  - -W
  dependencies:
  - hspec >= 2.7.10 && < 3
